const STORAGE_DATA = {
  config: {
    background: "/test-case/images/backgrounds/mobile-bg.png",
    // background
    cardStart: "/test-case/images/backgrounds/mobile-start-visual.jpg",
    cardLoading: "/test-case/images/backgrounds/mobile-loading-bg.png",
    cardQuestion: "/test-case/images/backgrounds/question-bg.png",
    cardQuestion_1: "/test-case/images/backgrounds/question-bg-1.jpg",
    cardQuestion_2: "/test-case/images/backgrounds/question-bg-2.jpg",
    cardQuestion_3: "/test-case/images/backgrounds/question-bg-3.jpg",
    cardQuestion_4: "/test-case/images/backgrounds/question-bg-4.jpg",
    cardQuestion_5: "/test-case/images/backgrounds/question-bg-5.jpg",
    cardQuestion_6: "/test-case/images/backgrounds/question-bg-6.jpg",
    cardQuestion_7: "/test-case/images/backgrounds/question-bg-7.jpg",
    cardQuestion_8: "/test-case/images/backgrounds/question-bg-8.jpg",
    cardQuestion_9: "/test-case/images/backgrounds/question-bg-9.jpg",
    cardQuestion_10: "/test-case/images/backgrounds/question-bg-10.jpg",
    //result blocks
    cardResult: "/test-case/images/result/結果頁底圖-(長).png",
    formBlock: "/test-case/images/form-block.png",
    wash_share: "/test-case/images/result/wash-share-clean.png",
    clickToParticipateBtn: "/test-case/images/buttons/click-to-participate-btn.png",
    popup: "/test-case/images/result/手機板-POP UP.png",
    //loading
    loadingVisual: "/test-case/images/backgrounds/desktop-loading-visual.png",
    loadingCaption: "/test-case/images/backgrounds/desktop-loading-bar-cap.png",
    // footer
    superMediaLogoLink: "/test-case/images/footer/super-media-logo.png",
    // questions
    questions: [
      { id: 1, text: "" },
      { id: 2, text: "" },
      { id: 3, text: "" },
      { id: 4, text: "" },
      { id: 5, text: "" },
      { id: 6, text: "" },
      { id: 7, text: "" },
      { id: 8, text: "" },
      { id: 9, text: "" },
      { id: 10, text: "" },
    ],
    buttons: {
      startButton: "/test-case/images/buttons/start-button.png",
      shareButton: "/test-case/images/buttons/share-button.png",
      restartButton: "/test-case/images/buttons/restart-button.png",
      backButton: "/test-case/images/buttons/back-button.png",
      detailsButton: "/test-case/images/buttons/details-button.png",
    },
    result: {
      outcomeHint: "/test-case/images/buttons/outcome-hint-button.png",
      resultA: "/test-case/images/result/A-boss.png",
      resultB: "/test-case/images/result/B-seeds.png",
      resultC: "/test-case/images/result/C-hotpot.png",
      resultD: "/test-case/images/result/D-egg.png",
      resultE: "/test-case/images/result/E-buffet.png",
      result0: "/test-case/images/result/O-feast.png",
    },
    links: {
      PARTICIPATE: "https://events.aromase.com.tw/p/scalp_dandruff-285?utm_source=website&utm_medium=scalpdandruff&utm_campaign=fever",
      PRODUCT: "https://www.aromase.com.tw/categories/scalp-dandruff?utm_source=website&utm_medium=scalpdandruff&utm_campaign=product",
    },
    desktop: {
      background: "/test-case/images/backgrounds/desktop-background.png",
      cardStart: "/test-case/images/backgrounds/網頁版_封面.jpg",
      cardLoading: "/test-case/images/backgrounds/desktop-loading-bg.png",
      cardQuestion_1: "/test-case/images/backgrounds/網頁版_Q1.jpg",
      cardQuestion_2: "/test-case/images/backgrounds/網頁版_Q2.jpg",
      cardQuestion_3: "/test-case/images/backgrounds/網頁版_Q3.jpg",
      cardQuestion_4: "/test-case/images/backgrounds/網頁版_Q4.jpg",
      cardQuestion_5: "/test-case/images/backgrounds/網頁版_Q5.jpg",
      cardQuestion_6: "/test-case/images/backgrounds/網頁版_Q6.jpg",
      cardQuestion_7: "/test-case/images/backgrounds/網頁版_Q7.jpg",
      cardQuestion_8: "/test-case/images/backgrounds/網頁版_Q8.jpg",
      cardQuestion_9: "/test-case/images/backgrounds/網頁版_Q9.jpg",
      cardQuestion_10: "/test-case/images/backgrounds/網頁版_Q10.jpg",
      //result
      cardResult: "/test-case/images/result/desktop-background-result.png",
      formBlock: "/test-case/images/result/form-block-desktop.png",
      propaganda_01: "/test-case/images/propaganda_01_light.png",
      propaganda_02: "/test-case/images/propaganda_02_water.png",
      wash_share: "/test-case/images/result/網頁版-02.png",
      clickToParticipateBtn: "/test-case/images/buttons/click-to-participate-btn.png",
      popup: "/test-case/images/result/網頁版-POP UP.png",
      buttons: {
        outcomeHint: "/test-case/images/result/網頁版-04.png",
        restartButton: "/test-case/images/result/網頁版-03.png",
        shareButton: "/test-case/images/result/網頁版-05.png",
      },
    },
  },
};

export default STORAGE_DATA;
