const STORAGE_DATA = {
    config: {
      mobile: {
        header: {
          logo: "/test-case/images/mobile/1按鈕＿艾瑪絲白logo.png",
          openbtn: "/test-case/images/mobile/1按鈕＿漢堡選單.png",
          closebtn: "/test-case/images/mobile/1按鈕＿叉叉.png",
          rightArrow: "/test-case/images/mobile/1按鈕＿小右箭頭.png",
          icon: "/test-case/images/mobile/1按鈕＿Ａ回官網.png",
          fb: "/test-case/images/mobile/1按鈕＿FB.png",
          gameWhite: "/test-case/images/mobile/1按鈕＿馬上測白.png",
          gameGreen: "/test-case/images/mobile/1按鈕＿馬上測綠.png",
          free: "/test-case/images/mobile/1按鈕＿限量.png",
          prize: "/test-case/images/mobile/1按鈕＿月月.png",
          video: "/test-case/images/mobile/1按鈕＿影音.png",
          recommend: "/test-case/images/mobile/1按鈕＿有感.png",
          level: "/test-case/images/mobile/1按鈕＿頭皮屑.png",
          real: "/test-case/images/mobile/1按鈕＿真人.png",
        },
        banner: "/test-case/images/mobile/1主視覺.webp",
        ctaImage: "/test-case/images/mobile/1按鈕＿懸浮加賴.png",
        gameSection: {
          title: "/test-case/images/mobile/2標題＿壓力大.png",
          background: "/test-case/images/mobile/2心測頁背景.webp",
          card: "/test-case/images/mobile/手機板_封面.jpg",
        },
        freeSection: {
          product: "/test-case/images/mobile/3新品限量免費體驗.png",
          background: "/test-case/images/mobile/3申請表單底圖.webp",
          tableBackground: "/test-case/images/mobile/3申請試用框.png",
          ctaFree: "/test-case/images/mobile/3按鈕＿立即申請.png",
          ctaProduct: "/test-case/images/mobile/3按紐＿了解去屑.png",
          ctaNote: "/test-case/images/mobile/3跳出視窗.png",
          confirm: "/test-case/images/mobile/3按紐＿確認同意.png",
        },
        prizeSection: {
          background: "/test-case/images/mobile/4洗後分享頁面.webp",
          cta: "/test-case/images/mobile/4按鈕＿點我參加.png",
        },
        videoSection:{
          background: "/test-case/images/mobile/5影音直擊底圖.webp",
          leftArrow: "/test-case/images/mobile/5左鍵.png",
          rightArrow: "/test-case/images/mobile/5右鍵.png",
          rowCard: "/test-case/images/mobile/5橫式影片框.png",
          columnCard: "/test-case/images/mobile/5直式影片框.png",
          card1title: "/test-case/images/mobile/5標題1（暫時款）.png",
          card2title: "/test-case/images/mobile/5標題2（暫時款）.png",
          card3title: "/test-case/images/mobile/5標題3（暫時款）.png",
        },
        recommendSection: {
          background: "/test-case/images/mobile/6有感推薦底圖.webp",
          card1title: "/test-case/images/mobile/6標題4（暫時款）.png",
          card2title: "/test-case/images/mobile/6標題5（暫時款）.png",
        },
        levelSection: {
          background: "/test-case/images/mobile/7擺脫頭皮困擾.webp",
        },
        realSection: {
          background: "/test-case/images/mobile/8真人證實.webp",
        },
        footer: {
          background: "/test-case/images/mobile/9footer.png",
          icon: "/test-case/images/mobile/9按鈕＿官網.png",
          fb: "/test-case/images/mobile/9按鈕＿fb.png",
          line: "/test-case/images/mobile/9按鈕＿line.png",
          ig: "/test-case/images/mobile/9按鈕＿ig.png",
          messager: "/test-case/images/mobile/9按鈕＿messenger.png",
          yt: "/test-case/images/mobile/9按鈕＿yt.png",
        },
      },
      desktop: {
        header:{
          logo: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-02.png",
          icon: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-03.png",
          fb: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-04.png",
          gameWhite: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-05.png",
          gameGreen: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-06.png",
          free: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-07-1.png",
          freeHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-07-1hover.png",
          prize: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-08-1.png",
          prizeHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-08-1hover.png",
          video: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-09.png",
          videoHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-13.png",
          recommend: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-10.png",
          recommendHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-14.png",
          level: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-11.png",
          levelHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-15.png",
          real: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-12.png",
          realHover: "/test-case/images/desktop/01_heading/01_艾瑪絲_Heading-16.png",
        },
        banner: "/test-case/images/desktop/02_主視覺/02_艾瑪絲_主視覺-懸浮按鈕.jpg",
        ctaImage: "/test-case/images/desktop/02_主視覺/02_艾瑪絲_主視覺-懸浮按鈕-02.png",
        gameSection: {
          background: "/test-case/images/desktop/03_心測小遊戲/03_艾瑪絲_壓力大頭皮屑也跟著控飆-01.webp",
          title: "/test-case/images/desktop/03_心測小遊戲/03_艾瑪絲_壓力大頭皮屑也跟著控飆-02.png",
          text: "/test-case/images/desktop/03_心測小遊戲/03_艾瑪絲_壓力大頭皮屑也跟著控飆-03.png",
          card: "/test-case/images/desktop/03_心測小遊戲/網頁版_封面.jpg",
        },
        freeSection: {
          background: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-01.webp",
          title: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-02.png",
          text: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-03.png",
          subText: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-04.png",
          tableBackground: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-05.png",
          ctaProduct: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-06.png",
          ctaProductHover: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-06-hover.png",
          ctaFree: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-07.png",
          ctaFreeHover: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-07-hover.png",
          ctaNote: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-08.png",
          confirm: "/test-case/images/desktop/04_新品免費體驗/04_艾瑪絲_新品限量免費體驗-09.png",
        },
        prizeSection: {
          background: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-01.webp",
          title: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-02.png",
          text: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-03.png",
          card: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-04.png",
          cta: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-05.png",
          ctaHover: "/test-case/images/desktop/05_月月抽千元/05_艾瑪絲_洗後分享月月抽千元-05-hover.png",
        },
        videoSection: {
          background: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-01.webp",
          title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-02.png",
          text: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-03.png",
          rowCard: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-04.png",
          columnCard: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-05.png",
          card1title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-06.png",
          card2title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-07.png",
          card3title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-08.png",
          card4title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-09.png",
          card5title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-10.png",
          card6title: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-11.png",
          leftArrow: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-12.png",
          rightArrow: "/test-case/images/desktop/06_影音區/06_艾瑪絲_影音直擊有感分享-13.png",
        },
        recommendSection: {
          background: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-01.webp",
          title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-02.png",
          text: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-03.png",
          rowCard: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-04.png",
          card1title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-05.png",
          card2title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-06.png",
          card3title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-07.png",
          card4title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-08.png",
          card5title: "/test-case/images/desktop/07_圖文區/07_艾瑪絲_有感推薦無藥去屑更安心-09.png",
        },
        levelSection: {
          background: "/test-case/images/desktop/08_頭皮檢測區/08_艾瑪絲_擺脫頭皮困擾重啟健康頭皮能量-01.webp",
          title: "/test-case/images/desktop/08_頭皮檢測區/08_艾瑪絲_擺脫頭皮困擾重啟健康頭皮能量-02.png",
          text: "/test-case/images/desktop/08_頭皮檢測區/08_艾瑪絲_擺脫頭皮困擾重啟健康頭皮能量-03.png",
          subText: "/test-case/images/desktop/08_頭皮檢測區/08_艾瑪絲_擺脫頭皮困擾重啟健康頭皮能量-04.png",
          image: "/test-case/images/desktop/08_頭皮檢測區/08_艾瑪絲_擺脫頭皮困擾重啟健康頭皮能量-05.png",
        },
        realSection: {
          background: "/test-case/images/desktop/09_真人實證區/09_艾瑪絲_真人實證去屑超有感.webp",
        },
        footer: {
          background: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-01.webp",
          icon: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-02.png",
          line: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-03.png",
          ig: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-04.png",
          yt: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-05.png",
          fb: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-06.png",
          messager: "/test-case/images/desktop/10_footer/10_艾瑪絲_Fotter-07.png",
        },
      },
      links: {
        official:"https://www.aromase.com.tw/?utm_source=website&utm_medium=scalpdandruff&utm_campaign=home",
        fb: "https://www.facebook.com/Aromase.tw",
        line: "https://maac.io/3nipQ",
        prize: "https://events.aromase.com.tw/p/scalp_dandruff-285?utm_source=website&utm_medium=scalpdandruff&utm_campaign=fever",
        ig: "https://www.instagram.com/aromasetw/?hl=zh-tw",
        yt: "https://www.youtube.com/channel/UCQNUfzP5_AOQZzf1Rb79s5w",
        messager: "https://m.me/146697988676586",
        ctaProduct: "https://www.aromase.com.tw/products/5%CE%B1-juniper-anti-dandruff-shampoo",
        PARTICIPATE: "https://events.aromase.com.tw/p/scalp_dandruff-285?utm_source=website&utm_medium=scalpdandruff&utm_campaign=fever",
        PRODUCT: "https://www.aromase.com.tw/categories/scalp-dandruff?utm_source=website&utm_medium=scalpdandruff&utm_campaign=product",  
      }
    },
  };
  
  export default STORAGE_DATA;